services:
  db:
    image: postgres:16
    container_name: freela-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: freela
      POSTGRES_USER: freela
      POSTGRES_PASSWORD: freela_password
    ports:
      - "5432:5432"
    volumes:
      - freela_pg_data:/var/lib/postgresql/data
  redis:
    image: redis:7-alpine
    container_name: freela-redis
    restart: unless-stopped
    ports:
      - "6379:6379"

volumes:
  freela_pg_data:
